language: python

matrix:
  include:
    - python: 3.4
      dist: trusty
      sudo: false
    - python: 3.5
      dist: trusty
      sudo: false
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true

services:
 - docker
install:
 - pip install -U pip wheel
 - pip install -r requirements.txt .
 - pip list
before_script:
  - openssl version -a
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
script:
 - python -m pytest -x zeronet/plugins/CryptMessage/Test
 - python -m pytest -x zeronet/plugins/Bigfile/Test
 - python -m pytest -x zeronet/plugins/AnnounceLocal/Test
 - python -m pytest -x zeronet/plugins/OptionalManager/Test
 - python -m pytest zeronet/Test --cov=src --cov-config zeronet/Test/coverage.ini
 - mv zeronet/plugins/disabled-Multiuser zeronet/plugins/Multiuser && python -m pytest -x zeronet/plugins/Multiuser/Test
 - mv zeronet/plugins/disabled-Bootstrapper zeronet/plugins/Bootstrapper && python -m pytest -x zeronet/plugins/Bootstrapper/Test
before_install:
  - pip install -U pytest mock pytest-cov selenium
  - pip install codecov
  - pip install coveralls
  # - docker build -t zeronet .
  # - docker run -d -v $PWD:/root/data -p 15441:15441 -p 127.0.0.1:43110:43110 zeronet
after_success:
  - codecov
  - coveralls --rcfile=zeronet/Test/coverage.ini
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    recipients:
      hello@zeronet.io
    on_success: change
