from setuptools import setup, find_packages

setup(
    name="zeronet",
    version='0.7.0',
    url='https://zeronet.io',
    license='GPL',
    description="Decentralized websites using Bitcoin crypto and BitTorrent network",
    author='Tamas Kocsis',
    author_email='tamas@zeronet.io',
    packages=find_packages(exclude=['zeronet.Test']),
    entry_points={
        'console_scripts': [
            'zeronet = zeronet.main:start',
        ],
    },
    package_data={'zeronet': [
        'lib/openssl/*.cnf',
        'lib/pybitcointools/wordlists/*',
        'Ui/template/*',
        'Ui/media/*',
        'Ui/media/*/*',
        'plugins/*/media/*',
        'plugins/*/media/*/*',
        'plugins/*/media/*/*/*',
        'plugins/Sidebar/media_globe/*',
    ]},
    python_requires=">=3.0",
    install_requires=[ # requirements.txt is downstream of this
        'gevent>=1.1.0',
        'msgpack>=0.4.4',
        'base58',
        'merkletools',
        'pyelliptic==1.5.6',
        'rsa',
        'PySocks',
        'pyasn1',
        'websocket_client',
        'gevent-websocket',
        'bencode.py',
        'coincurve',
        'python-bitcoinlib',
        'maxminddb',
        'Werkzeug', # for interactive console at /Console URL
    ],
    tests_require=['pytest', 'pytest-cov', 'mock'],
    classifiers=[
        'Operating System :: Unix',
        'Operating System :: Microsoft :: Windows',
        'Environment :: MacOS X',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Development Status :: 4 - Beta',
        'Topic :: Communications',
        'Topic :: Communications :: BBS',
        'Topic :: Communications :: Chat',
        'Topic :: Communications :: Email',
        'Topic :: Communications :: File Sharing',
        'Topic :: WWW/HTTP',
        'Topic :: WWW/HTTP :: Dynamic Content',
        'Topic :: System :: Distributed Computing',
        'Topic :: Security :: Cryptography',
        'Topic :: Database',
    ],
)
